name: Tests

on:
  push:
  pull_request:

jobs:
  tests_linux:
    name: PHP ${{ matrix.php }} Linux
    runs-on: ubuntu
    strategy:
      matrix:
        php: ['8.3', '8.4']

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:snapshot
          coverage: none

      - name: Setup Problem Matchers
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - uses: ramsey/composer-install@v3
      - name: Execute PHPUnit
        run: vendor/bin/phpunit